version: "3.8"
services:
    php-httpd:
        build:
            context: ./webserver
            #Permet de localiser le dockerfile à build, celui-ci n'étant pas sur le Hub
        ports:
            - "4444:80"
        volumes:
            #Simple bind pour monter un répertoire local sur le serveur web
            - website:/var/www/localhost/htdocs
        networks:
            - backend

    mariadb:
        image: mariadb:10.5.2
        volumes:
            #On a ici un volume dédié afin d'assurer la persistance de la DB après extinction du conteneur
            - mariadb-volume:/var/lib/mysql
        environment:
            TZ: "Europe/Rome"
            #Le reste est importé depuis un fichier pour respecter l'extériorisation de la config
            MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        networks:
            - backend
volumes:
    website:
    mariadb-volume:
networks:
    backend: